# Generated by Django 5.0.7 on 2024-11-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='daily_return',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
