# Generated by Django 5.0.7 on 2024-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliovaluehistory_daily_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostock',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
