# Generated by Django 5.0.7 on 2024-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_upvotes_count_portfolioupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioupvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
