# Generated by Django 5.0.7 on 2024-11-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stock_lists', '0002_alter_favoritestocklist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritestocklist',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
