# Generated by Django 5.0.7 on 2024-08-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('enterprise_value', models.BigIntegerField(blank=True, null=True)),
                ('trailing_pe', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('peg_ratio', models.FloatField(blank=True, null=True)),
                ('price_to_book', models.FloatField(blank=True, null=True)),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('gross_profit', models.BigIntegerField(blank=True, null=True)),
                ('ebitda', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('diluted_eps', models.FloatField(blank=True, null=True)),
                ('total_cash', models.BigIntegerField(blank=True, null=True)),
                ('total_debt', models.BigIntegerField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('dividend_rate', models.FloatField(blank=True, null=True)),
                ('payout_ratio', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_high', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_low', models.FloatField(blank=True, null=True)),
                ('average_daily_volume', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='equity_optimizer.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'date'], name='equity_opti_stock_i_ff41e3_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
