# Generated by Django 5.0.7 on 2024-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='daily_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='trend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
