# Generated by Django 5.0.7 on 2024-08-22 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity_optimizer', '0002_stockdata_daily_return_stockdata_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
