# Generated by Django 5.0.7 on 2024-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity_optimizer', '0004_stock_created_at_stock_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='adj_close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open',
            field=models.FloatField(),
        ),
    ]
