# Generated by Django 5.0.7 on 2024-11-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity_optimizer', '0006_alter_stock_created_at_alter_stock_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='average_daily_volume',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stock',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='book_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='esg_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ex_dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fifty_day_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='forward_eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='full_time_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='long_business_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='trailing_eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
