# Generated by Django 5.0.7 on 2024-11-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity_optimizer', '0001_initial_squashed_0008_stock_delisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='adj_close_to_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
