# Generated by Django 5.0.7 on 2024-11-06 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField()),
                ('profile_link', models.URLField()),
                ('age', models.IntegerField()),
                ('investor_level', models.CharField(choices=[('Professional', 'Professional'), ('Retail', 'Retail'), ('Eligible', 'Eligible')], max_length=30)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
