# Generated by Django 5.0.7 on 2024-11-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='investor_level',
            field=models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Retail', 'Retail'), ('Eligible', 'Eligible')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
